### ISSUE TITLE
clone-azure-vm.ps1 - Output private IP address

### ISSUE THREAD

**Issue by muhtehwuush** [Irfan95/azure-powershell#1]
For "clone-azure-vm.ps1" - output the private IP address inside your "connection details of the VM" section. 

Good for people who do not use public IP address to access their VMs.

**Comment by Irfan95** [comment]
Fixed as per version 1.1.3
- Added Private IP address output at end of script

**Comment by muhtehwuush** [comment]
@Irfan95 Took you a while :)
